name: mapton
title: Mapton
base: core22
version: '3.1.0'
summary: Some kind of map application
description: |
    **Mapton is an open-source map application** for Linux, MacOS and Windows that lets you explore the world.


    Mapton consists of a rich set of background maps and a toolbox, a toolbox that like the maps, can be extended with custom plugins.


    _It's a simple application, yet a powerful platform._


    **Features**
    * 3d objects, 4d when looking at time coded data
    * Time slider
    * Geographical bookmarks and Point of Interests
    * Layer management
    * WMS support
    * Measuring tools
    * Extensible with custom plugins


    **Bundled plugins**
    * Files - Plot kml files
    * Photos - Plot geotagged images
    * Population visualizer - Look at the world population
    * Wikipedia - Find and read geotagged articles
    * XKCD - View the amazing XKCD strip

    https://twitter.com/mapton_app

grade: stable
architectures: [ amd64 ]
confinement: strict
icon: snap/gui/mapton.png
license: Apache-2.0

apps:
  mapton:
    command: mapton/bin/mapton
    extensions: [gnome]
    plugs:
        - home
        - removable-media
        - network

parts:
  mapton:
    plugin: dump
    #source: https://github.com/trixon/mapton/releases/download/v$SNAPCRAFT_PROJECT_VERSION/mapton-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source: /root/project/mapton-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source-type: zip

  config:
    after:
      - mapton
    plugin: nil
    override-prime: |
        sed -i 's/${HOME}\/.${APPNAME}/${SNAP_USER_COMMON}\/.mapton/' /root/prime/mapton/bin/mapton
        sed -i 's/${HOME}\/.cache\/${APPNAME}/${SNAP_USER_COMMON}\/.cache\/mapton/' /root/prime/mapton/bin/mapton
        rm -r /root/prime/mapton/platform/modules/lib/i386
        rm -r /root/prime/mapton/platform/modules/lib/x86
        rm /root/prime/mapton/platform/lib/*.dll
        rm /root/prime/mapton/platform/lib/*.exe
